apiVersion: apps/v1
kind: Deployment

metadata:
  name: front-user

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: front-user

  template:
    metadata:
      labels:
        app: front-user

    spec:
      containers:
        - name: front-user
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}