apiVersion: apps/v1
kind: Deployment

metadata:
  name: front-admin

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: front-admin

  template:
    metadata:
      labels:
        app: front-admin

    spec:
      containers:
        - name: front-admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}